### ISSUE TITLE
VSCodium support

### ISSUE THREAD

**Issue by diggit** [dcelasun/pkgbuilds#2]
Hi,
I can see, that you maintain `visual-studio-code-bin` and `visual-studio-code-sinsiders`.

Do you have plans to add [VSCodium](https://github.com/VSCodium/vscodium) which is cleaned up oss version of VScode? There are binary builds, so I think, that PKGBUILD would be similar to mentioned above.

**Comment by dcelasun** [comment]
Hi!

Unbranded versions of Visual Studio Code already exist on AUR under [code](https://aur.archlinux.org/packages/code/) and [code-git](https://aur.archlinux.org/packages/code-git/). If VSCodium is not doing something materially different than those packages, I suggest you use them.
